import { FileInfo } from "./filter.js";
import { extname } from "path";

export interface RepoSection {
  owner: string;
  repo: string;
  ref?: string;
  files: FileInfo[];
  totalTokens: number;
}

function getLanguage(relativePath: string) {
  const ext = extname(relativePath).toLowerCase();
  const langMap: Record<string, string> = {
    ".ts": "typescript",
    ".tsx": "tsx",
    ".js": "javascript",
    ".jsx": "jsx",
    ".json": "json",
    ".md": "markdown",
    ".vue": "vue",
    ".svelte": "svelte",
    ".html": "html",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".css": "css",
    ".scss": "scss",
  };

  return langMap[ext] || "unknown";
}

export function formatMarkdown(sections: RepoSection[], totalBudget: number) {
  const lines: string[] = [];
  let usedTokens = 0;

  // Header
  lines.push("# LLM Context\n");
  lines.push(
    `> Generated by breach | Token budget: ${totalBudget.toLocaleString()}\n`,
  );

  // ToC
  lines.push("## Repositories\n");
  for (const section of sections) {
    lines.push(
      `- **${section.owner}/${section.repo}** (${section.files.length} files, ~${section.totalTokens.toLocaleString()} tokens)`,
    );
  }
  lines.push("");

  // Each repo section
  for (const section of sections) {
    lines.push("---\n");
    lines.push(
      `## ${section.owner}/${section.repo}${section.ref ? ` (${section.ref})` : ""}\n`,
    );

    // Group files by category
    const byCategory = new Map<string, FileInfo[]>();
    for (const file of section.files) {
      const cat = file.category;
      if (!byCategory.has(cat)) byCategory.set(cat, []);
      byCategory.get(cat)!.push(file);
    }

    const categoryOrder = [
      "types",
      "exports",
      "tests",
      "examples",
      "config",
      "source",
    ];

    for (const category of categoryOrder) {
      const files = byCategory.get(category);

      if (!files || files.length === 0) continue;

      lines.push(
        `### ${category.charAt(0).toUpperCase() + category.slice(1)}\n`,
      );

      for (const file of files) {
        usedTokens += file.tokens;
        const language = getLanguage(file.relativePath);

        lines.push(`#### \`${file.relativePath}\`\n`);
        lines.push("```" + language);
        lines.push(file.content);
        lines.push("```\n");
      }
    }
  }

  lines.push("---\n");
  lines.push(
    `> Total tokens used: ~${usedTokens.toLocaleString()} / ${totalBudget.toLocaleString()}`,
  );

  return lines.join("\n");
}

export function formatXML(sections: RepoSection[], totalBudget: number) {
  const lines: string[] = [];
  let usedTokens = 0;

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(`<context budget="${totalBudget}">`);

  for (const section of sections) {
    lines.push(
      `  <repository owner="${section.owner}" name="${section.repo}" ${section.ref ? ` ref="${section.ref}"` : ""}>`,
    );

    for (const file of section.files) {
      usedTokens += file.tokens;

      lines.push(
        `    <file name="${file.relativePath}" category="${file.category}" tokens="${file.tokens}">`,
      );
      lines.push(`<![CDATA[${file.content}]]>`);
      lines.push(`    </file>`);
    }

    lines.push(`  </repository>`);
  }

  lines.push(`  <meta tokens_used="${usedTokens}" />`);
  lines.push(`</context>`);

  return lines.join("\n");
}
